### ISSUE TITLE
option to print test output for debugging

### ISSUE THREAD

**Issue by DBarthe** [GoogleCloudPlatform/marketplace-testrunner#3]
Hello, this is more a question than a issue.

I can't find an option to print the full output (stdin and stderr) of bashTest when failed. I've seen people using  `set -x` but can't figure out how to get this output printed.

I would expect a `debug: true` or something. Is there something I missed ?

Thanks

**Comment by ovk6** [comment]
Hi @DBarthe 

Additional info on stdout / stderr / exitcode is added in this PR: #14
New image is available under: gcr.io/cloud-marketplace-tools/testrunner:0.1.4 tag
